### ISSUE TITLE
Grunt tab should be hidden by default

### ISSUE THREAD

**Issue by eddiemonge** [nickclaw/atom-grunt-runner#13]
It currently takes up a lot of space and is intrusive

**Comment by faddee** [comment]
:+1:

**Comment by ealves-pt** [comment]
This PR #67 adds that possibility. There is an option in the package settings.

**Comment by kokarn** [comment]
This is now live on master. As soon as @nickclaw publishes a new version you should be good.
If you can't wait that long you can install the latest version from master :)
