### ISSUE TITLE
Colours are almost impossible to read on a light shell theme

### ISSUE THREAD

**Issue by aaronpowell** [nickclaw/atom-grunt-runner#38]
I use a light shell theme and it's basically impossible to read the warning messages because of the yellow.

![Log](https://cloud.githubusercontent.com/assets/434140/6517227/19afdde4-c3ed-11e4-92ad-39d37b42b175.PNG)

The blue isn't much better but I can at least read that. I hacked my own CSS to use `#aa0` to it's a bit more readable :stuck_out_tongue:

**Comment by kokarn** [comment]
Yeah, it's hardcoded right now which of course makes it horrible on some
themes. Sorry about that. Would you mind having a go at trying to use some
colours from the current theme? I hope there are some vars defined
somewhere ^^

**Comment by ealves-pt** [comment]
Possible fix in PR #68

**Comment by kokarn** [comment]
Fixed with #68. It's on master now so if you install from there you'll get it. 
Otherwise there will hopefully be a new version soon-ish :)
