### ISSUE TITLE
Panel not opening as default any more

### ISSUE THREAD

**Issue by kokarn** [nickclaw/atom-grunt-runner#40]
After the last update, the panels don't open as before. Now i have to go and toggle panel for it to open an horizontal panel and then toggle log to show the default vertical log.

Is that the same behaviour as anybody else? @adam-h ?

**Comment by adam-h** [comment]
I never saw that issue, but I see it's been/being fixed in the other issue :)

**Comment by kokarn** [comment]
Agreed, it is now fixed thanks to @sebastianhaeni
