### ISSUE TITLE
Grunt file (Gruntfile.js) fails to be loaded if it uses mocha

### ISSUE THREAD

**Issue by Gum-Joe** [nickclaw/atom-grunt-runner#64]
![screenshot 33](https://cloud.githubusercontent.com/assets/12299307/9980259/8ad79ca4-5f89-11e5-9190-29d989eff477.png)
![screenshot 34](https://cloud.githubusercontent.com/assets/12299307/9980267/9fc7fb18-5f89-11e5-90fd-623c77c70759.png)

Even when the grunt file is open, it still does not detect it.

System:
* Atom 1.0.13
* Grunt-runner v0.11.0
* Grunt v0.4.5
* Grunt-cli v0.1.13
* OS: Windows 8.1

**Comment by kokarn** [comment]
Is the Gruntfile in the root or somewhere else?

**Comment by Gum-Joe** [comment]
It is in the root

**Comment by kokarn** [comment]
Can you run grunt from the commandline in that project? I've had problems when either I forgot to run npm install or the gruntfile isn't formatted as it should :/

**Comment by Gum-Joe** [comment]
Yes, I can 
![screenshot 38](https://cloud.githubusercontent.com/assets/12299307/9996350/8b0a0a7c-607e-11e5-9a90-a06f0cdd762f.png)

**Comment by Arcath** [comment]
I am getting something similar on my Windows 10 machine, grunt works fine from powershell but the gruntfile is not detected...

doing some debugging myself the gruntfile is found and loaded but there is a EPERM error when trying to run it to get the task list. Assuming that this is to do with the loading of tasks from NPM I commented all my `grunt.loadNpmTasks` lines and BINGO it works fine.

After adding each one in turn it seems to be `grunt-mocha-test` that is killing my gruntfile.

Try commenting it out in yours and see if it works

**Comment by kokarn** [comment]
@Gum-Joe Can you try the latest version from master and see if that solves the issue? It's with the fix from #65.

**Comment by Arcath** [comment]
More testing has shown that the issue is in https://github.com/pghalliday/grunt-mocha-test/blob/master/tasks/lib/MochaWrapper.js which when allowed to load causes an EPERM error. Will do some more debugging shortly

**Comment by Arcath** [comment]
Seems now to be because that file is where Mocha is being required... comment out the require('mocha') and it will parse ok

**Comment by Gum-Joe** [comment]
Ok, will update

**Comment by Gum-Joe** [comment]
Where is the require('mocha') line of code

**Comment by Gum-Joe** [comment]
NEW ERROR
Thanks @Arcath for that pull request that improved error handleing - the error is now:
`Error loading gruntfile: Error parsing Gruntfile. EPERM: operation not permitted, write (C:\Users\Kishan Sambhi\Documents\Projects\Web-OS/Gruntfile)`

**Comment by kokarn** [comment]
Great, thanks @Arcath!

That seems to be the exact same problem he was having with mocha fucking up somehow.

The only thing that might be is that you are on windows and i'm unsure if that's even supported at the moment, haven't tried for like a year :P Does it work with any other gruntfile or if you comment out the mocha stuff?

**Comment by Gum-Joe** [comment]
Thanks everyone for your help - can now run grunt tasks after commenting out mocha
![screenshot 39](https://cloud.githubusercontent.com/assets/12299307/10077545/9aa15d6c-62d8-11e5-8c6b-947f949316c4.png)

**Comment by Arcath** [comment]
@Gum-Joe only issue is if you want to run mocha grunt tasks. For now I am using [grunt-shell](https://github.com/sindresorhus/grunt-shell) to run mocha commands manually for me

**Comment by Gum-Joe** [comment]
Ok

**Comment by Gum-Joe** [comment]
I will use grunt-exec

**Comment by Gum-Joe** [comment]
I've changed the title as that is now the issue

**Comment by kokarn** [comment]
@Arcath have you found that this bug is due to something with mocha or atom-grunt-runner?

**Comment by Gum-Joe** [comment]
It is an issue with grunt-mocha-contribute, so it is probably mocha or grunt-mocha-contribute

**Comment by Gum-Joe** [comment]
Will create issue on grunt-mocha-contrib

**Comment by kokarn** [comment]
Great!

So I take it I can close this for now then?

**Comment by Gum-Joe** [comment]
Yes

**Comment by Gum-Joe** [comment]
Will open new issue
