### ISSUE TITLE
Gruntfile not found

### ISSUE THREAD

**Issue by kwhc** [nickclaw/atom-grunt-runner#74]
Log says "Error loading gruntfile: Gruntfile not found" when Gruntfile.js is present.

**Comment by techseo** [comment]
I have the same issue for one project folder... uninstall, rename, reboot, npm install, etc. didn't help. Gruntfile.js works just fine via console.

**Comment by techseo** [comment]
Okay, guess I've found the problem: The gruntfile will not be found if your path contains whitespaces.

**Comment by kokarn** [comment]
Closing as duplicate
